#ifndef _SDK_CONFIG_H
#define _SDK_CONFIG_H

#define CONFIG_ESP_FACE_DETECT_ENABLED 0
#define CONFIG_ESP_FACE_RECOGNITION_ENABLED 0
#define CONFIG_LED_ILLUMINATOR_ENABLED 1
#define CONFIG_LED_LEDC_PIN 4
#define CONFIG_LED_MAX_INTENSITY 255
#define CONFIG_LED_LEDC_LOW_SPEED_MODE 1
#define CONFIG_LED_LEDC_TIMER 1
#define CONFIG_LED_LEDC_CHANNEL LEDC_CHANNEL_1

#endif
